apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mellan
  namespace: blamtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mellan
    spec:
      containers:
      - command:
        - node
        - mellan.js
        image: blam/grpc-test:v1.6.0
        resources:
          requests:
            memory: 2.1Gi
            cpu: 1.8
        name: mellan
        ports:
        - containerPort: 8443
        livenessProbe:
          tcpSocket:
            port: 8443
          failureThreshold: 30
          initialDelaySeconds: 200
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 8443
          failureThreshold: 30
          initialDelaySeconds: 200
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: mellan
  namespace: blamtest
spec:
  selector:
    app: mellan
  type: NodePort
  ports:
  - port: 8443
    targetPort: 8443
